### ISSUE TITLE
st9-projective缺少库文件

### ISSUE THREAD

**Issue by peitianyu** [Unsigned-Long/slam-tricks#1]
我在尝试编译st9-projective过程中缺少
```
#include "artwork/geometry/point.hpp"
#include "artwork/logger/logger.h"
```
请问大佬, 这些是那个库文件呀

**Comment by Unsigned-Long** [comment]
不好意思，当时写的时候没考到这件事。这里的logger和geometry都是自己之前写的小玩意。可以在这里找到：
https://github.com/Unsigned-Long/geometry.git
https://github.com/Unsigned-Long/logger.git
编译后make install安装即可（好像都是header-only的库，不需要链接库文件）。
logger库还是比较好用的，我一直在用，输出调试代码的时候比较方便。比如可以直接打印vector之类的容器等等。😊

**Comment by peitianyu** [comment]
> 不好意思，当时写的时候没考到这件事。这里的logger和geometry都是自己之前写的小玩意。可以在这里找到： https://github.com/Unsigned-Long/geometry.git https://github.com/Unsigned-Long/logger.git 编译后make install安装即可（好像都是header-only的库，不需要链接库文件）。 logger库还是比较好用的，我一直在用，输出调试代码的时候比较方便。比如可以直接打印vector之类的容器等等。😊

可以可以, 感谢~ 不过那么卷的吗? 现在还没睡

**Comment by Unsigned-Long** [comment]
睡前突然邮箱看见这条消息^&^,
